### ISSUE TITLE
نیاز به داشتن FarsiLibrary

### ISSUE THREAD

**Issue by majnouni** [ghost1372/ClassSRM#3]
سلام زمانیکه پروژه رو به 
devexpress 17.2.3 
کانورت میکنم از فارسی لابراری ایراد میگیره و میگه فقط باید کامپوننت های 
17.1 
رو به سورس اضافه کنید

میشه راهنمایی کنید

**Comment by ghost1372** [comment]
سلام باید کتابخانه core فارسی لایبرری رو هم با 
devexpress جدیدتر هماهنگ کنید تا چند دقیقه دیگه کامیت جدید میزنم و با اخرین نسخه هماهنگ میکنم

**Comment by majnouni** [comment]
ممنونم - فقط 
datenavigator 
رو چه جوری میشه فارسی کرد ، ؟


آیا پروژه به صورت آزاد می نویسید ؟

**Comment by ghost1372** [comment]
فارسی هست دیگه
برخی پروژه هام رو بصورت ازاد منتشر میکنم

**Comment by majnouni** [comment]
یعنی فقط کافی من datenavigator رو 
drag & drop konam ?
نیاز نیست توی قسمت 
designer تغییراتی بدم ؟

--------------------------------------
و سوال دوم 
میخوام بدونم پروژه برنامه نویسی انجام میدید ؟
------------------------------

**Comment by majnouni** [comment]
![11111](https://user-images.githubusercontent.com/34125969/33504661-8d0eff10-d6fd-11e7-99d1-d80e2de6b5a8.png)
toye project shoma date farsi injori neveshte mishe
می خوام ببینم چه جوری میشه اینکارو کرد
